services:
  # Backend API
  - type: web
    name: snowflake-mcp-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      # External PostgreSQL connection string
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: PORT_RANGE_START
        value: "8100"
      - key: PORT_RANGE_END
        value: "8200"
      - key: PYTHON_VERSION
        value: "3.11.0"

  # Frontend
  - type: web
    name: snowflake-mcp-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
